//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.23 at 08:20:34 AM BST 
//


package com.se.datex2.schema;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A measured or calculated value of the concentration of vehicles on a unit stretch of road in a given direction.
 * 
 * <p>Java class for ConcentrationOfVehiclesValue complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConcentrationOfVehiclesValue">
 *   &lt;complexContent>
 *     &lt;extension base="{http://datex2.eu/schema/2/2_0}DataValue">
 *       &lt;sequence>
 *         &lt;element name="concentrationOfVehicles" type="{http://datex2.eu/schema/2/2_0}ConcentrationVehiclesPerKilometre"/>
 *         &lt;element name="concentrationOfVehiclesValueExtension" type="{http://datex2.eu/schema/2/2_0}_ExtensionType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConcentrationOfVehiclesValue", propOrder = {
    "concentrationOfVehicles",
    "concentrationOfVehiclesValueExtension"
})
public class ConcentrationOfVehiclesValue
    extends DataValue
{

    @XmlElement(required = true)
    protected BigInteger concentrationOfVehicles;
    protected ExtensionType concentrationOfVehiclesValueExtension;

    /**
     * Gets the value of the concentrationOfVehicles property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getConcentrationOfVehicles() {
        return concentrationOfVehicles;
    }

    /**
     * Sets the value of the concentrationOfVehicles property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setConcentrationOfVehicles(BigInteger value) {
        this.concentrationOfVehicles = value;
    }

    /**
     * Gets the value of the concentrationOfVehiclesValueExtension property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionType }
     *     
     */
    public ExtensionType getConcentrationOfVehiclesValueExtension() {
        return concentrationOfVehiclesValueExtension;
    }

    /**
     * Sets the value of the concentrationOfVehiclesValueExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionType }
     *     
     */
    public void setConcentrationOfVehiclesValueExtension(ExtensionType value) {
        this.concentrationOfVehiclesValueExtension = value;
    }

}
