//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.30 at 10:48:06 AM GMT 
//


package com.se.datex2.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConstructionWorkTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ConstructionWorkTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="blastingWork"/>
 *     &lt;enumeration value="constructionWork"/>
 *     &lt;enumeration value="demolitionWork"/>
 *     &lt;enumeration value="roadImprovementOrUpgrading"/>
 *     &lt;enumeration value="roadWideningWork"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ConstructionWorkTypeEnum")
@XmlEnum
public enum ConstructionWorkTypeEnum {


    /**
     * Blasting or quarrying work at the specified location.
     * 
     */
    @XmlEnumValue("blastingWork")
    BLASTING_WORK("blastingWork"),

    /**
     * Construction work of a general nature at the specified location.
     * 
     */
    @XmlEnumValue("constructionWork")
    CONSTRUCTION_WORK("constructionWork"),

    /**
     * Demolition work associated with the construction work.
     * 
     */
    @XmlEnumValue("demolitionWork")
    DEMOLITION_WORK("demolitionWork"),

    /**
     * Construction work associated with improvements to the road or its layout or with it upgrading.
     * 
     */
    @XmlEnumValue("roadImprovementOrUpgrading")
    ROAD_IMPROVEMENT_OR_UPGRADING("roadImprovementOrUpgrading"),

    /**
     * Road widening work at the specified location.
     * 
     */
    @XmlEnumValue("roadWideningWork")
    ROAD_WIDENING_WORK("roadWideningWork");
    private final String value;

    ConstructionWorkTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ConstructionWorkTypeEnum fromValue(String v) {
        for (ConstructionWorkTypeEnum c: ConstructionWorkTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
