//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.23 at 08:20:34 AM BST 
//


package com.se.datex2.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DelayBandEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DelayBandEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="negligible"/>
 *     &lt;enumeration value="upToTenMinutes"/>
 *     &lt;enumeration value="betweenTenMinutesAndThirtyMinutes"/>
 *     &lt;enumeration value="betweenThirtyMinutesAndOneHour"/>
 *     &lt;enumeration value="betweenOneHourAndThreeHours"/>
 *     &lt;enumeration value="betweenThreeHoursAndSixHours"/>
 *     &lt;enumeration value="longerThanSixHours"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DelayBandEnum")
@XmlEnum
public enum DelayBandEnum {


    /**
     * Negligible delay.
     * 
     */
    @XmlEnumValue("negligible")
    NEGLIGIBLE("negligible"),

    /**
     * Delay up to ten minutes.
     * 
     */
    @XmlEnumValue("upToTenMinutes")
    UP_TO_TEN_MINUTES("upToTenMinutes"),

    /**
     * Delay between ten minutes and thirty minutes.
     * 
     */
    @XmlEnumValue("betweenTenMinutesAndThirtyMinutes")
    BETWEEN_TEN_MINUTES_AND_THIRTY_MINUTES("betweenTenMinutesAndThirtyMinutes"),

    /**
     * Delay between thirty minutes and one hour.
     * 
     */
    @XmlEnumValue("betweenThirtyMinutesAndOneHour")
    BETWEEN_THIRTY_MINUTES_AND_ONE_HOUR("betweenThirtyMinutesAndOneHour"),

    /**
     * Delay between one hour and three hours.
     * 
     */
    @XmlEnumValue("betweenOneHourAndThreeHours")
    BETWEEN_ONE_HOUR_AND_THREE_HOURS("betweenOneHourAndThreeHours"),

    /**
     * Delay between three hours and six hours.
     * 
     */
    @XmlEnumValue("betweenThreeHoursAndSixHours")
    BETWEEN_THREE_HOURS_AND_SIX_HOURS("betweenThreeHoursAndSixHours"),

    /**
     * Delay longer than six hours.
     * 
     */
    @XmlEnumValue("longerThanSixHours")
    LONGER_THAN_SIX_HOURS("longerThanSixHours");
    private final String value;

    DelayBandEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DelayBandEnum fromValue(String v) {
        for (DelayBandEnum c: DelayBandEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
