//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.30 at 10:48:06 AM GMT 
//


package com.se.datex2.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EmergencyServiceStatusEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EmergencyServiceStatusEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="requested"/>
 *     &lt;enumeration value="attending"/>
 *     &lt;enumeration value="none"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EmergencyServiceStatusEnum")
@XmlEnum
public enum EmergencyServiceStatusEnum {


    /**
     * The emergency service has been requested to attend, but is not yet in attendance.
     * 
     */
    @XmlEnumValue("requested")
    REQUESTED("requested"),

    /**
     * The emergency service is in attendance.
     * 
     */
    @XmlEnumValue("attending")
    ATTENDING("attending"),

    /**
     * The service has no involvement in the situation/event.
     * 
     */
    @XmlEnumValue("none")
    NONE("none");
    private final String value;

    EmergencyServiceStatusEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EmergencyServiceStatusEnum fromValue(String v) {
        for (EmergencyServiceStatusEnum c: EmergencyServiceStatusEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
