//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.30 at 10:48:06 AM GMT 
//


package com.se.datex2.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EquipmentOrSystemTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EquipmentOrSystemTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="anprCameras"/>
 *     &lt;enumeration value="automatedTollSystem"/>
 *     &lt;enumeration value="cctvCameras"/>
 *     &lt;enumeration value="emergencyRoadsideTelephones"/>
 *     &lt;enumeration value="galleryLights"/>
 *     &lt;enumeration value="laneControlSigns"/>
 *     &lt;enumeration value="levelCrossing"/>
 *     &lt;enumeration value="matrixSigns"/>
 *     &lt;enumeration value="rampControls"/>
 *     &lt;enumeration value="roadsideCommunicationsSystem"/>
 *     &lt;enumeration value="roadsidePowerSystem"/>
 *     &lt;enumeration value="speedControlSigns"/>
 *     &lt;enumeration value="streetLighting"/>
 *     &lt;enumeration value="temporaryTrafficLights"/>
 *     &lt;enumeration value="tollGates"/>
 *     &lt;enumeration value="trafficLightSets"/>
 *     &lt;enumeration value="trafficSignals"/>
 *     &lt;enumeration value="tunnelLights"/>
 *     &lt;enumeration value="tunnelVentilation"/>
 *     &lt;enumeration value="variableMessageSigns"/>
 *     &lt;enumeration value="other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EquipmentOrSystemTypeEnum")
@XmlEnum
public enum EquipmentOrSystemTypeEnum {


    /**
     * Automatic number plate recognition cameras.
     * 
     */
    @XmlEnumValue("anprCameras")
    ANPR_CAMERAS("anprCameras"),

    /**
     * Automated toll system.
     * 
     */
    @XmlEnumValue("automatedTollSystem")
    AUTOMATED_TOLL_SYSTEM("automatedTollSystem"),

    /**
     * Closed-circuit television cameras.
     * 
     */
    @XmlEnumValue("cctvCameras")
    CCTV_CAMERAS("cctvCameras"),

    /**
     * Emergency roadside telephones.
     * 
     */
    @XmlEnumValue("emergencyRoadsideTelephones")
    EMERGENCY_ROADSIDE_TELEPHONES("emergencyRoadsideTelephones"),

    /**
     * Gallery lights.
     * 
     */
    @XmlEnumValue("galleryLights")
    GALLERY_LIGHTS("galleryLights"),

    /**
     * Signs used to control lane usage (e.g. in tidal flow systems or hard shoulder running).
     * 
     */
    @XmlEnumValue("laneControlSigns")
    LANE_CONTROL_SIGNS("laneControlSigns"),

    /**
     * Level crossing (barriers and signals).
     * 
     */
    @XmlEnumValue("levelCrossing")
    LEVEL_CROSSING("levelCrossing"),

    /**
     * Matrix signs. These normally comprise a symbol display area surrounded by four lights (usually amber) which flash when a symbol is displayed. 
     * 
     */
    @XmlEnumValue("matrixSigns")
    MATRIX_SIGNS("matrixSigns"),

    /**
     * Ramp control equipment.
     * 
     */
    @XmlEnumValue("rampControls")
    RAMP_CONTROLS("rampControls"),

    /**
     * Roadside communications system which is used by one or more roadside equipments or systems.
     * 
     */
    @XmlEnumValue("roadsideCommunicationsSystem")
    ROADSIDE_COMMUNICATIONS_SYSTEM("roadsideCommunicationsSystem"),

    /**
     * Roadside power system which is used by one or more roadside equipments or systems.
     * 
     */
    @XmlEnumValue("roadsidePowerSystem")
    ROADSIDE_POWER_SYSTEM("roadsidePowerSystem"),

    /**
     * Signs used to control traffic speed.
     * 
     */
    @XmlEnumValue("speedControlSigns")
    SPEED_CONTROL_SIGNS("speedControlSigns"),

    /**
     * Street or road lighting.
     * 
     */
    @XmlEnumValue("streetLighting")
    STREET_LIGHTING("streetLighting"),

    /**
     * Temporary traffic lights.
     * 
     */
    @XmlEnumValue("temporaryTrafficLights")
    TEMPORARY_TRAFFIC_LIGHTS("temporaryTrafficLights"),

    /**
     * Toll gates.
     * 
     */
    @XmlEnumValue("tollGates")
    TOLL_GATES("tollGates"),

    /**
     * Sets of traffic lights.
     * 
     */
    @XmlEnumValue("trafficLightSets")
    TRAFFIC_LIGHT_SETS("trafficLightSets"),

    /**
     * Traffic signals.
     * 
     */
    @XmlEnumValue("trafficSignals")
    TRAFFIC_SIGNALS("trafficSignals"),

    /**
     * Tunnel lights.
     * 
     */
    @XmlEnumValue("tunnelLights")
    TUNNEL_LIGHTS("tunnelLights"),

    /**
     * Tunnel ventilation system.
     * 
     */
    @XmlEnumValue("tunnelVentilation")
    TUNNEL_VENTILATION("tunnelVentilation"),

    /**
     * Variable message signs.
     * 
     */
    @XmlEnumValue("variableMessageSigns")
    VARIABLE_MESSAGE_SIGNS("variableMessageSigns"),

    /**
     * Other than as defined in this enumeration.
     * 
     */
    @XmlEnumValue("other")
    OTHER("other");
    private final String value;

    EquipmentOrSystemTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EquipmentOrSystemTypeEnum fromValue(String v) {
        for (EquipmentOrSystemTypeEnum c: EquipmentOrSystemTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
