//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.30 at 10:48:06 AM GMT 
//


package com.se.datex2.schema;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The status of the damage associated with a type of infrastructure.
 * 
 * <p>Java class for InfrastructureDamageStatus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InfrastructureDamageStatus">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="infrastructureType" type="{http://datex2.eu/schema/2/2_0}InfrastructureTypeEnum"/>
 *         &lt;element name="numberOfItemsDamaged" type="{http://datex2.eu/schema/2/2_0}NonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="lengthDamaged" type="{http://datex2.eu/schema/2/2_0}MetresAsNonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="infrastructureDamageStatusExtension" type="{http://datex2.eu/schema/2/2_0}_ExtensionType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InfrastructureDamageStatus", propOrder = {
    "infrastructureType",
    "numberOfItemsDamaged",
    "lengthDamaged",
    "infrastructureDamageStatusExtension"
})
public class InfrastructureDamageStatus {

    @XmlElement(required = true)
    protected InfrastructureTypeEnum infrastructureType;
    protected BigInteger numberOfItemsDamaged;
    protected BigInteger lengthDamaged;
    protected ExtensionType infrastructureDamageStatusExtension;

    /**
     * Gets the value of the infrastructureType property.
     * 
     * @return
     *     possible object is
     *     {@link InfrastructureTypeEnum }
     *     
     */
    public InfrastructureTypeEnum getInfrastructureType() {
        return infrastructureType;
    }

    /**
     * Sets the value of the infrastructureType property.
     * 
     * @param value
     *     allowed object is
     *     {@link InfrastructureTypeEnum }
     *     
     */
    public void setInfrastructureType(InfrastructureTypeEnum value) {
        this.infrastructureType = value;
    }

    /**
     * Gets the value of the numberOfItemsDamaged property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfItemsDamaged() {
        return numberOfItemsDamaged;
    }

    /**
     * Sets the value of the numberOfItemsDamaged property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfItemsDamaged(BigInteger value) {
        this.numberOfItemsDamaged = value;
    }

    /**
     * Gets the value of the lengthDamaged property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLengthDamaged() {
        return lengthDamaged;
    }

    /**
     * Sets the value of the lengthDamaged property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLengthDamaged(BigInteger value) {
        this.lengthDamaged = value;
    }

    /**
     * Gets the value of the infrastructureDamageStatusExtension property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionType }
     *     
     */
    public ExtensionType getInfrastructureDamageStatusExtension() {
        return infrastructureDamageStatusExtension;
    }

    /**
     * Sets the value of the infrastructureDamageStatusExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionType }
     *     
     */
    public void setInfrastructureDamageStatusExtension(ExtensionType value) {
        this.infrastructureDamageStatusExtension = value;
    }

}
