//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.30 at 10:48:06 AM GMT 
//


package com.se.datex2.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.se.datex2.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _D2LogicalModel_QNAME = new QName("http://datex2.eu/schema/2/2_0", "d2LogicalModel");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.se.datex2.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MultilingualString }
     * 
     */
    public MultilingualString createMultilingualString() {
        return new MultilingualString();
    }

    /**
     * Create an instance of {@link D2LogicalModel }
     * 
     */
    public D2LogicalModel createD2LogicalModel() {
        return new D2LogicalModel();
    }

    /**
     * Create an instance of {@link Subjects }
     * 
     */
    public Subjects createSubjects() {
        return new Subjects();
    }

    /**
     * Create an instance of {@link SituationParent }
     * 
     */
    public SituationParent createSituationParent() {
        return new SituationParent();
    }

    /**
     * Create an instance of {@link VmsPublication }
     * 
     */
    public VmsPublication createVmsPublication() {
        return new VmsPublication();
    }

    /**
     * Create an instance of {@link AxleWeight }
     * 
     */
    public AxleWeight createAxleWeight() {
        return new AxleWeight();
    }

    /**
     * Create an instance of {@link PcuFlowValue }
     * 
     */
    public PcuFlowValue createPcuFlowValue() {
        return new PcuFlowValue();
    }

    /**
     * Create an instance of {@link RccInformation }
     * 
     */
    public RccInformation createRccInformation() {
        return new RccInformation();
    }

    /**
     * Create an instance of {@link GenericPublication }
     * 
     */
    public GenericPublication createGenericPublication() {
        return new GenericPublication();
    }

    /**
     * Create an instance of {@link MeasurementSpecificCharacteristics }
     * 
     */
    public MeasurementSpecificCharacteristics createMeasurementSpecificCharacteristics() {
        return new MeasurementSpecificCharacteristics();
    }

    /**
     * Create an instance of {@link WidthCharacteristic }
     * 
     */
    public WidthCharacteristic createWidthCharacteristic() {
        return new WidthCharacteristic();
    }

    /**
     * Create an instance of {@link Point }
     * 
     */
    public Point createPoint() {
        return new Point();
    }

    /**
     * Create an instance of {@link NonManagedCause }
     * 
     */
    public NonManagedCause createNonManagedCause() {
        return new NonManagedCause();
    }

    /**
     * Create an instance of {@link PrecipitationDetail }
     * 
     */
    public PrecipitationDetail createPrecipitationDetail() {
        return new PrecipitationDetail();
    }

    /**
     * Create an instance of {@link VehicleObstructionExtensionType }
     * 
     */
    public VehicleObstructionExtensionType createVehicleObstructionExtensionType() {
        return new VehicleObstructionExtensionType();
    }

    /**
     * Create an instance of {@link ElaboratedData }
     * 
     */
    public ElaboratedData createElaboratedData() {
        return new ElaboratedData();
    }

    /**
     * Create an instance of {@link SiteMeasurementsIndexMeasuredValue }
     * 
     */
    public SiteMeasurementsIndexMeasuredValue createSiteMeasurementsIndexMeasuredValue() {
        return new SiteMeasurementsIndexMeasuredValue();
    }

    /**
     * Create an instance of {@link VmsSupplementaryPanel }
     * 
     */
    public VmsSupplementaryPanel createVmsSupplementaryPanel() {
        return new VmsSupplementaryPanel();
    }

    /**
     * Create an instance of {@link AuthorityOperation }
     * 
     */
    public AuthorityOperation createAuthorityOperation() {
        return new AuthorityOperation();
    }

    /**
     * Create an instance of {@link DirectionCompassValue }
     * 
     */
    public DirectionCompassValue createDirectionCompassValue() {
        return new DirectionCompassValue();
    }

    /**
     * Create an instance of {@link EmergencyServiceStatus }
     * 
     */
    public EmergencyServiceStatus createEmergencyServiceStatus() {
        return new EmergencyServiceStatus();
    }

    /**
     * Create an instance of {@link VmsPictogramUK }
     * 
     */
    public VmsPictogramUK createVmsPictogramUK() {
        return new VmsPictogramUK();
    }

    /**
     * Create an instance of {@link TrafficView }
     * 
     */
    public TrafficView createTrafficView() {
        return new TrafficView();
    }

    /**
     * Create an instance of {@link Period }
     * 
     */
    public Period createPeriod() {
        return new Period();
    }

    /**
     * Create an instance of {@link OverallPeriod }
     * 
     */
    public OverallPeriod createOverallPeriod() {
        return new OverallPeriod();
    }

    /**
     * Create an instance of {@link WeatherConditions }
     * 
     */
    public WeatherConditions createWeatherConditions() {
        return new WeatherConditions();
    }

    /**
     * Create an instance of {@link DateTimeValue }
     * 
     */
    public DateTimeValue createDateTimeValue() {
        return new DateTimeValue();
    }

    /**
     * Create an instance of {@link AlertCMethod2Linear }
     * 
     */
    public AlertCMethod2Linear createAlertCMethod2Linear() {
        return new AlertCMethod2Linear();
    }

    /**
     * Create an instance of {@link VersionedReference }
     * 
     */
    public VersionedReference createVersionedReference() {
        return new VersionedReference();
    }

    /**
     * Create an instance of {@link VehicleFlowValue }
     * 
     */
    public VehicleFlowValue createVehicleFlowValue() {
        return new VehicleFlowValue();
    }

    /**
     * Create an instance of {@link CarParks }
     * 
     */
    public CarParks createCarParks() {
        return new CarParks();
    }

    /**
     * Create an instance of {@link UrlLink }
     * 
     */
    public UrlLink createUrlLink() {
        return new UrlLink();
    }

    /**
     * Create an instance of {@link TpegGeometricArea }
     * 
     */
    public TpegGeometricArea createTpegGeometricArea() {
        return new TpegGeometricArea();
    }

    /**
     * Create an instance of {@link PrecipitationInformation }
     * 
     */
    public PrecipitationInformation createPrecipitationInformation() {
        return new PrecipitationInformation();
    }

    /**
     * Create an instance of {@link VmsTextDisplayCharacteristics }
     * 
     */
    public VmsTextDisplayCharacteristics createVmsTextDisplayCharacteristics() {
        return new VmsTextDisplayCharacteristics();
    }

    /**
     * Create an instance of {@link VmsPictogramDisplayArea }
     * 
     */
    public VmsPictogramDisplayArea createVmsPictogramDisplayArea() {
        return new VmsPictogramDisplayArea();
    }

    /**
     * Create an instance of {@link DayWeekMonth }
     * 
     */
    public DayWeekMonth createDayWeekMonth() {
        return new DayWeekMonth();
    }

    /**
     * Create an instance of {@link SiteMeasurements }
     * 
     */
    public SiteMeasurements createSiteMeasurements() {
        return new SiteMeasurements();
    }

    /**
     * Create an instance of {@link TpegSimplePoint }
     * 
     */
    public TpegSimplePoint createTpegSimplePoint() {
        return new TpegSimplePoint();
    }

    /**
     * Create an instance of {@link VmsUnitVmsIndexVms }
     * 
     */
    public VmsUnitVmsIndexVms createVmsUnitVmsIndexVms() {
        return new VmsUnitVmsIndexVms();
    }

    /**
     * Create an instance of {@link TrafficSpeedExtensionType }
     * 
     */
    public TrafficSpeedExtensionType createTrafficSpeedExtensionType() {
        return new TrafficSpeedExtensionType();
    }

    /**
     * Create an instance of {@link SituationManagement }
     * 
     */
    public SituationManagement createSituationManagement() {
        return new SituationManagement();
    }

    /**
     * Create an instance of {@link DurationValue }
     * 
     */
    public DurationValue createDurationValue() {
        return new DurationValue();
    }

    /**
     * Create an instance of {@link PointByCoordinates }
     * 
     */
    public PointByCoordinates createPointByCoordinates() {
        return new PointByCoordinates();
    }

    /**
     * Create an instance of {@link VmsPictogram }
     * 
     */
    public VmsPictogram createVmsPictogram() {
        return new VmsPictogram();
    }

    /**
     * Create an instance of {@link VmsTextLine }
     * 
     */
    public VmsTextLine createVmsTextLine() {
        return new VmsTextLine();
    }

    /**
     * Create an instance of {@link VmsTablePublication }
     * 
     */
    public VmsTablePublication createVmsTablePublication() {
        return new VmsTablePublication();
    }

    /**
     * Create an instance of {@link TpegIlcPointDescriptor }
     * 
     */
    public TpegIlcPointDescriptor createTpegIlcPointDescriptor() {
        return new TpegIlcPointDescriptor();
    }

    /**
     * Create an instance of {@link TrafficHeadway }
     * 
     */
    public TrafficHeadway createTrafficHeadway() {
        return new TrafficHeadway();
    }

    /**
     * Create an instance of {@link Source }
     * 
     */
    public Source createSource() {
        return new Source();
    }

    /**
     * Create an instance of {@link SituationRecordVersionedReference }
     * 
     */
    public SituationRecordVersionedReference createSituationRecordVersionedReference() {
        return new SituationRecordVersionedReference();
    }

    /**
     * Create an instance of {@link LocationContainedInItinerary }
     * 
     */
    public LocationContainedInItinerary createLocationContainedInItinerary() {
        return new LocationContainedInItinerary();
    }

    /**
     * Create an instance of {@link SituationVersionedReference }
     * 
     */
    public SituationVersionedReference createSituationVersionedReference() {
        return new SituationVersionedReference();
    }

    /**
     * Create an instance of {@link KilogramsConcentrationValue }
     * 
     */
    public KilogramsConcentrationValue createKilogramsConcentrationValue() {
        return new KilogramsConcentrationValue();
    }

    /**
     * Create an instance of {@link VmsPictogramDisplayAreaPictogramSequencingIndexVmsPictogram }
     * 
     */
    public VmsPictogramDisplayAreaPictogramSequencingIndexVmsPictogram createVmsPictogramDisplayAreaPictogramSequencingIndexVmsPictogram() {
        return new VmsPictogramDisplayAreaPictogramSequencingIndexVmsPictogram();
    }

    /**
     * Create an instance of {@link VmsUnitFault }
     * 
     */
    public VmsUnitFault createVmsUnitFault() {
        return new VmsUnitFault();
    }

    /**
     * Create an instance of {@link PredefinedNonOrderedLocationGroupVersionedReference }
     * 
     */
    public PredefinedNonOrderedLocationGroupVersionedReference createPredefinedNonOrderedLocationGroupVersionedReference() {
        return new PredefinedNonOrderedLocationGroupVersionedReference();
    }

    /**
     * Create an instance of {@link MicrogramsConcentrationValue }
     * 
     */
    public MicrogramsConcentrationValue createMicrogramsConcentrationValue() {
        return new MicrogramsConcentrationValue();
    }

    /**
     * Create an instance of {@link TpegJunction }
     * 
     */
    public TpegJunction createTpegJunction() {
        return new TpegJunction();
    }

    /**
     * Create an instance of {@link GeneralObstruction }
     * 
     */
    public GeneralObstruction createGeneralObstruction() {
        return new GeneralObstruction();
    }

    /**
     * Create an instance of {@link PredefinedItineraryIndexPredefinedLocation }
     * 
     */
    public PredefinedItineraryIndexPredefinedLocation createPredefinedItineraryIndexPredefinedLocation() {
        return new PredefinedItineraryIndexPredefinedLocation();
    }

    /**
     * Create an instance of {@link PercentageDistanceAlongLinearElement }
     * 
     */
    public PercentageDistanceAlongLinearElement createPercentageDistanceAlongLinearElement() {
        return new PercentageDistanceAlongLinearElement();
    }

    /**
     * Create an instance of {@link VmsPictogramDisplayAreaIndexPictogramDisplayAreaSettings }
     * 
     */
    public VmsPictogramDisplayAreaIndexPictogramDisplayAreaSettings createVmsPictogramDisplayAreaIndexPictogramDisplayAreaSettings() {
        return new VmsPictogramDisplayAreaIndexPictogramDisplayAreaSettings();
    }

    /**
     * Create an instance of {@link AlertCMethod4PrimaryPointLocation }
     * 
     */
    public AlertCMethod4PrimaryPointLocation createAlertCMethod4PrimaryPointLocation() {
        return new AlertCMethod4PrimaryPointLocation();
    }

    /**
     * Create an instance of {@link GeneralNetworkManagement }
     * 
     */
    public GeneralNetworkManagement createGeneralNetworkManagement() {
        return new GeneralNetworkManagement();
    }

    /**
     * Create an instance of {@link PointAlongLinearElement }
     * 
     */
    public PointAlongLinearElement createPointAlongLinearElement() {
        return new PointAlongLinearElement();
    }

    /**
     * Create an instance of {@link Pollution }
     * 
     */
    public Pollution createPollution() {
        return new Pollution();
    }

    /**
     * Create an instance of {@link HeaderInformation }
     * 
     */
    public HeaderInformation createHeaderInformation() {
        return new HeaderInformation();
    }

    /**
     * Create an instance of {@link SpeedPercentile }
     * 
     */
    public SpeedPercentile createSpeedPercentile() {
        return new SpeedPercentile();
    }

    /**
     * Create an instance of {@link VmsManagedLogicalLocation }
     * 
     */
    public VmsManagedLogicalLocation createVmsManagedLogicalLocation() {
        return new VmsManagedLogicalLocation();
    }

    /**
     * Create an instance of {@link Referent }
     * 
     */
    public Referent createReferent() {
        return new Referent();
    }

    /**
     * Create an instance of {@link TpegHeight }
     * 
     */
    public TpegHeight createTpegHeight() {
        return new TpegHeight();
    }

    /**
     * Create an instance of {@link LinearWithinLinearElement }
     * 
     */
    public LinearWithinLinearElement createLinearWithinLinearElement() {
        return new LinearWithinLinearElement();
    }

    /**
     * Create an instance of {@link TextDisplayAreaSettings }
     * 
     */
    public TextDisplayAreaSettings createTextDisplayAreaSettings() {
        return new TextDisplayAreaSettings();
    }

    /**
     * Create an instance of {@link VehicleCharacteristics }
     * 
     */
    public VehicleCharacteristics createVehicleCharacteristics() {
        return new VehicleCharacteristics();
    }

    /**
     * Create an instance of {@link ReroutingManagement }
     * 
     */
    public ReroutingManagement createReroutingManagement() {
        return new ReroutingManagement();
    }

    /**
     * Create an instance of {@link AreaExtension }
     * 
     */
    public AreaExtension createAreaExtension() {
        return new AreaExtension();
    }

    /**
     * Create an instance of {@link MultilingualStringValue }
     * 
     */
    public MultilingualStringValue createMultilingualStringValue() {
        return new MultilingualStringValue();
    }

    /**
     * Create an instance of {@link PredefinedLocationVersionedReference }
     * 
     */
    public PredefinedLocationVersionedReference createPredefinedLocationVersionedReference() {
        return new PredefinedLocationVersionedReference();
    }

    /**
     * Create an instance of {@link NonWeatherRelatedRoadConditions }
     * 
     */
    public NonWeatherRelatedRoadConditions createNonWeatherRelatedRoadConditions() {
        return new NonWeatherRelatedRoadConditions();
    }

    /**
     * Create an instance of {@link LinearWithinLinearElementExtensionType }
     * 
     */
    public LinearWithinLinearElementExtensionType createLinearWithinLinearElementExtensionType() {
        return new LinearWithinLinearElementExtensionType();
    }

    /**
     * Create an instance of {@link VmsTextLineIndexVmsTextLine }
     * 
     */
    public VmsTextLineIndexVmsTextLine createVmsTextLineIndexVmsTextLine() {
        return new VmsTextLineIndexVmsTextLine();
    }

    /**
     * Create an instance of {@link Spillage }
     * 
     */
    public Spillage createSpillage() {
        return new Spillage();
    }

    /**
     * Create an instance of {@link FilterReference }
     * 
     */
    public FilterReference createFilterReference() {
        return new FilterReference();
    }

    /**
     * Create an instance of {@link ItineraryByReference }
     * 
     */
    public ItineraryByReference createItineraryByReference() {
        return new ItineraryByReference();
    }

    /**
     * Create an instance of {@link AlertCMethod4SecondaryPointLocation }
     * 
     */
    public AlertCMethod4SecondaryPointLocation createAlertCMethod4SecondaryPointLocation() {
        return new AlertCMethod4SecondaryPointLocation();
    }

    /**
     * Create an instance of {@link VmsUnitTableVersionedReference }
     * 
     */
    public VmsUnitTableVersionedReference createVmsUnitTableVersionedReference() {
        return new VmsUnitTableVersionedReference();
    }

    /**
     * Create an instance of {@link VmsText }
     * 
     */
    public VmsText createVmsText() {
        return new VmsText();
    }

    /**
     * Create an instance of {@link AlertCArea }
     * 
     */
    public AlertCArea createAlertCArea() {
        return new AlertCArea();
    }

    /**
     * Create an instance of {@link ElaboratedDataFault }
     * 
     */
    public ElaboratedDataFault createElaboratedDataFault() {
        return new ElaboratedDataFault();
    }

    /**
     * Create an instance of {@link AlertCMethod2Point }
     * 
     */
    public AlertCMethod2Point createAlertCMethod2Point() {
        return new AlertCMethod2Point();
    }

    /**
     * Create an instance of {@link VmsUnitRecordVmsIndexVmsRecord }
     * 
     */
    public VmsUnitRecordVmsIndexVmsRecord createVmsUnitRecordVmsIndexVmsRecord() {
        return new VmsUnitRecordVmsIndexVmsRecord();
    }

    /**
     * Create an instance of {@link AlertCMethod2SecondaryPointLocation }
     * 
     */
    public AlertCMethod2SecondaryPointLocation createAlertCMethod2SecondaryPointLocation() {
        return new AlertCMethod2SecondaryPointLocation();
    }

    /**
     * Create an instance of {@link TpegJunctionPointDescriptor }
     * 
     */
    public TpegJunctionPointDescriptor createTpegJunctionPointDescriptor() {
        return new TpegJunctionPointDescriptor();
    }

    /**
     * Create an instance of {@link DisturbanceActivity }
     * 
     */
    public DisturbanceActivity createDisturbanceActivity() {
        return new DisturbanceActivity();
    }

    /**
     * Create an instance of {@link ApplicationRateValue }
     * 
     */
    public ApplicationRateValue createApplicationRateValue() {
        return new ApplicationRateValue();
    }

    /**
     * Create an instance of {@link MeasurementEquipmentFault }
     * 
     */
    public MeasurementEquipmentFault createMeasurementEquipmentFault() {
        return new MeasurementEquipmentFault();
    }

    /**
     * Create an instance of {@link Temperature }
     * 
     */
    public Temperature createTemperature() {
        return new Temperature();
    }

    /**
     * Create an instance of {@link PublicEventExtensionType }
     * 
     */
    public PublicEventExtensionType createPublicEventExtensionType() {
        return new PublicEventExtensionType();
    }

    /**
     * Create an instance of {@link PictogramDisplayAreaSettings }
     * 
     */
    public PictogramDisplayAreaSettings createPictogramDisplayAreaSettings() {
        return new PictogramDisplayAreaSettings();
    }

    /**
     * Create an instance of {@link VmsPictogramDisplayCharacteristics }
     * 
     */
    public VmsPictogramDisplayCharacteristics createVmsPictogramDisplayCharacteristics() {
        return new VmsPictogramDisplayCharacteristics();
    }

    /**
     * Create an instance of {@link RoadworksEventDetails }
     * 
     */
    public RoadworksEventDetails createRoadworksEventDetails() {
        return new RoadworksEventDetails();
    }

    /**
     * Create an instance of {@link TpegLinearLocation }
     * 
     */
    public TpegLinearLocation createTpegLinearLocation() {
        return new TpegLinearLocation();
    }

    /**
     * Create an instance of {@link DistanceFromLinearElementStart }
     * 
     */
    public DistanceFromLinearElementStart createDistanceFromLinearElementStart() {
        return new DistanceFromLinearElementStart();
    }

    /**
     * Create an instance of {@link PredefinedLocationsPublication }
     * 
     */
    public PredefinedLocationsPublication createPredefinedLocationsPublication() {
        return new PredefinedLocationsPublication();
    }

    /**
     * Create an instance of {@link PercentageValue }
     * 
     */
    public PercentageValue createPercentageValue() {
        return new PercentageValue();
    }

    /**
     * Create an instance of {@link VehicleObstruction }
     * 
     */
    public VehicleObstruction createVehicleObstruction() {
        return new VehicleObstruction();
    }

    /**
     * Create an instance of {@link MeasuredDataPublication }
     * 
     */
    public MeasuredDataPublication createMeasuredDataPublication() {
        return new MeasuredDataPublication();
    }

    /**
     * Create an instance of {@link InfrastructureDamageObstruction }
     * 
     */
    public InfrastructureDamageObstruction createInfrastructureDamageObstruction() {
        return new InfrastructureDamageObstruction();
    }

    /**
     * Create an instance of {@link PublicEvent }
     * 
     */
    public PublicEvent createPublicEvent() {
        return new PublicEvent();
    }

    /**
     * Create an instance of {@link VehicleCharacteristicsExtensionType }
     * 
     */
    public VehicleCharacteristicsExtensionType createVehicleCharacteristicsExtensionType() {
        return new VehicleCharacteristicsExtensionType();
    }

    /**
     * Create an instance of {@link NumberOfAxlesCharacteristic }
     * 
     */
    public NumberOfAxlesCharacteristic createNumberOfAxlesCharacteristic() {
        return new NumberOfAxlesCharacteristic();
    }

    /**
     * Create an instance of {@link AxleSpacing }
     * 
     */
    public AxleSpacing createAxleSpacing() {
        return new AxleSpacing();
    }

    /**
     * Create an instance of {@link GroupOfPeopleInvolved }
     * 
     */
    public GroupOfPeopleInvolved createGroupOfPeopleInvolved() {
        return new GroupOfPeopleInvolved();
    }

    /**
     * Create an instance of {@link IndividualLanesStatus }
     * 
     */
    public IndividualLanesStatus createIndividualLanesStatus() {
        return new IndividualLanesStatus();
    }

    /**
     * Create an instance of {@link HumidityInformation }
     * 
     */
    public HumidityInformation createHumidityInformation() {
        return new HumidityInformation();
    }

    /**
     * Create an instance of {@link ImpactExtensionType }
     * 
     */
    public ImpactExtensionType createImpactExtensionType() {
        return new ImpactExtensionType();
    }

    /**
     * Create an instance of {@link Humidity }
     * 
     */
    public Humidity createHumidity() {
        return new Humidity();
    }

    /**
     * Create an instance of {@link MeasurementSiteTablePublication }
     * 
     */
    public MeasurementSiteTablePublication createMeasurementSiteTablePublication() {
        return new MeasurementSiteTablePublication();
    }

    /**
     * Create an instance of {@link Situation }
     * 
     */
    public Situation createSituation() {
        return new Situation();
    }

    /**
     * Create an instance of {@link AlertCMethod4Point }
     * 
     */
    public AlertCMethod4Point createAlertCMethod4Point() {
        return new AlertCMethod4Point();
    }

    /**
     * Create an instance of {@link Visibility }
     * 
     */
    public Visibility createVisibility() {
        return new Visibility();
    }

    /**
     * Create an instance of {@link MeasurementSiteRecordVersionedReference }
     * 
     */
    public MeasurementSiteRecordVersionedReference createMeasurementSiteRecordVersionedReference() {
        return new MeasurementSiteRecordVersionedReference();
    }

    /**
     * Create an instance of {@link Conditions }
     * 
     */
    public Conditions createConditions() {
        return new Conditions();
    }

    /**
     * Create an instance of {@link RoadsideServiceDisruption }
     * 
     */
    public RoadsideServiceDisruption createRoadsideServiceDisruption() {
        return new RoadsideServiceDisruption();
    }

    /**
     * Create an instance of {@link TrafficStatusValue }
     * 
     */
    public TrafficStatusValue createTrafficStatusValue() {
        return new TrafficStatusValue();
    }

    /**
     * Create an instance of {@link AreaExtensionType }
     * 
     */
    public AreaExtensionType createAreaExtensionType() {
        return new AreaExtensionType();
    }

    /**
     * Create an instance of {@link Mobility }
     * 
     */
    public Mobility createMobility() {
        return new Mobility();
    }

    /**
     * Create an instance of {@link GenericPublicationExtensionType }
     * 
     */
    public GenericPublicationExtensionType createGenericPublicationExtensionType() {
        return new GenericPublicationExtensionType();
    }

    /**
     * Create an instance of {@link WinterDrivingManagement }
     * 
     */
    public WinterDrivingManagement createWinterDrivingManagement() {
        return new WinterDrivingManagement();
    }

    /**
     * Create an instance of {@link GroupOfVehiclesInvolved }
     * 
     */
    public GroupOfVehiclesInvolved createGroupOfVehiclesInvolved() {
        return new GroupOfVehiclesInvolved();
    }

    /**
     * Create an instance of {@link PointDestination }
     * 
     */
    public PointDestination createPointDestination() {
        return new PointDestination();
    }

    /**
     * Create an instance of {@link SourceSituation }
     * 
     */
    public SourceSituation createSourceSituation() {
        return new SourceSituation();
    }

    /**
     * Create an instance of {@link MaintenanceWorks }
     * 
     */
    public MaintenanceWorks createMaintenanceWorks() {
        return new MaintenanceWorks();
    }

    /**
     * Create an instance of {@link MeasurementSiteTableVersionedReference }
     * 
     */
    public MeasurementSiteTableVersionedReference createMeasurementSiteTableVersionedReference() {
        return new MeasurementSiteTableVersionedReference();
    }

    /**
     * Create an instance of {@link Impact }
     * 
     */
    public Impact createImpact() {
        return new Impact();
    }

    /**
     * Create an instance of {@link EnvironmentalObstruction }
     * 
     */
    public EnvironmentalObstruction createEnvironmentalObstruction() {
        return new EnvironmentalObstruction();
    }

    /**
     * Create an instance of {@link VmsSupplementaryPictogram }
     * 
     */
    public VmsSupplementaryPictogram createVmsSupplementaryPictogram() {
        return new VmsSupplementaryPictogram();
    }

    /**
     * Create an instance of {@link VmsDynamicCharacteristics }
     * 
     */
    public VmsDynamicCharacteristics createVmsDynamicCharacteristics() {
        return new VmsDynamicCharacteristics();
    }

    /**
     * Create an instance of {@link NonOrderedLocationGroupByList }
     * 
     */
    public NonOrderedLocationGroupByList createNonOrderedLocationGroupByList() {
        return new NonOrderedLocationGroupByList();
    }

    /**
     * Create an instance of {@link DelaysExtensionType }
     * 
     */
    public DelaysExtensionType createDelaysExtensionType() {
        return new DelaysExtensionType();
    }

    /**
     * Create an instance of {@link ExternalReferencing }
     * 
     */
    public ExternalReferencing createExternalReferencing() {
        return new ExternalReferencing();
    }

    /**
     * Create an instance of {@link VmsUnitTable }
     * 
     */
    public VmsUnitTable createVmsUnitTable() {
        return new VmsUnitTable();
    }

    /**
     * Create an instance of {@link SupplementaryPositionalDescription }
     * 
     */
    public SupplementaryPositionalDescription createSupplementaryPositionalDescription() {
        return new SupplementaryPositionalDescription();
    }

    /**
     * Create an instance of {@link AlternateRoutes }
     * 
     */
    public AlternateRoutes createAlternateRoutes() {
        return new AlternateRoutes();
    }

    /**
     * Create an instance of {@link LocationByReference }
     * 
     */
    public LocationByReference createLocationByReference() {
        return new LocationByReference();
    }

    /**
     * Create an instance of {@link Delays }
     * 
     */
    public Delays createDelays() {
        return new Delays();
    }

    /**
     * Create an instance of {@link LengthCharacteristic }
     * 
     */
    public LengthCharacteristic createLengthCharacteristic() {
        return new LengthCharacteristic();
    }

    /**
     * Create an instance of {@link WeatherRelatedRoadConditions }
     * 
     */
    public WeatherRelatedRoadConditions createWeatherRelatedRoadConditions() {
        return new WeatherRelatedRoadConditions();
    }

    /**
     * Create an instance of {@link PointCoordinates }
     * 
     */
    public PointCoordinates createPointCoordinates() {
        return new PointCoordinates();
    }

    /**
     * Create an instance of {@link InternationalIdentifier }
     * 
     */
    public InternationalIdentifier createInternationalIdentifier() {
        return new InternationalIdentifier();
    }

    /**
     * Create an instance of {@link AffectedCarriagewayAndLanes }
     * 
     */
    public AffectedCarriagewayAndLanes createAffectedCarriagewayAndLanes() {
        return new AffectedCarriagewayAndLanes();
    }

    /**
     * Create an instance of {@link MaintenanceWorksExtensionType }
     * 
     */
    public MaintenanceWorksExtensionType createMaintenanceWorksExtensionType() {
        return new MaintenanceWorksExtensionType();
    }

    /**
     * Create an instance of {@link TravelTimeData }
     * 
     */
    public TravelTimeData createTravelTimeData() {
        return new TravelTimeData();
    }

    /**
     * Create an instance of {@link ManagedCause }
     * 
     */
    public ManagedCause createManagedCause() {
        return new ManagedCause();
    }

    /**
     * Create an instance of {@link HazardousMaterials }
     * 
     */
    public HazardousMaterials createHazardousMaterials() {
        return new HazardousMaterials();
    }

    /**
     * Create an instance of {@link LocationCharacteristicsOverride }
     * 
     */
    public LocationCharacteristicsOverride createLocationCharacteristicsOverride() {
        return new LocationCharacteristicsOverride();
    }

    /**
     * Create an instance of {@link AlertCDirection }
     * 
     */
    public AlertCDirection createAlertCDirection() {
        return new AlertCDirection();
    }

    /**
     * Create an instance of {@link PrecipitationIntensityValue }
     * 
     */
    public PrecipitationIntensityValue createPrecipitationIntensityValue() {
        return new PrecipitationIntensityValue();
    }

    /**
     * Create an instance of {@link VehicleCurrentCharacteristics }
     * 
     */
    public VehicleCurrentCharacteristics createVehicleCurrentCharacteristics() {
        return new VehicleCurrentCharacteristics();
    }

    /**
     * Create an instance of {@link ImpactDetails }
     * 
     */
    public ImpactDetails createImpactDetails() {
        return new ImpactDetails();
    }

    /**
     * Create an instance of {@link MeasurementSiteRecordIndexMeasurementSpecificCharacteristics }
     * 
     */
    public MeasurementSiteRecordIndexMeasurementSpecificCharacteristics createMeasurementSiteRecordIndexMeasurementSpecificCharacteristics() {
        return new MeasurementSiteRecordIndexMeasurementSpecificCharacteristics();
    }

    /**
     * Create an instance of {@link VmsSupplementaryPanelCharacteristics }
     * 
     */
    public VmsSupplementaryPanelCharacteristics createVmsSupplementaryPanelCharacteristics() {
        return new VmsSupplementaryPanelCharacteristics();
    }

    /**
     * Create an instance of {@link IndividualVehicleDataValues }
     * 
     */
    public IndividualVehicleDataValues createIndividualVehicleDataValues() {
        return new IndividualVehicleDataValues();
    }

    /**
     * Create an instance of {@link Fault }
     * 
     */
    public Fault createFault() {
        return new Fault();
    }

    /**
     * Create an instance of {@link MaintenanceVehicles }
     * 
     */
    public MaintenanceVehicles createMaintenanceVehicles() {
        return new MaintenanceVehicles();
    }

    /**
     * Create an instance of {@link GeneralInstructionOrMessageToRoadUsers }
     * 
     */
    public GeneralInstructionOrMessageToRoadUsers createGeneralInstructionOrMessageToRoadUsers() {
        return new GeneralInstructionOrMessageToRoadUsers();
    }

    /**
     * Create an instance of {@link TrafficViewPublication }
     * 
     */
    public TrafficViewPublication createTrafficViewPublication() {
        return new TrafficViewPublication();
    }

    /**
     * Create an instance of {@link AreaDestination }
     * 
     */
    public AreaDestination createAreaDestination() {
        return new AreaDestination();
    }

    /**
     * Create an instance of {@link VmsMessage }
     * 
     */
    public VmsMessage createVmsMessage() {
        return new VmsMessage();
    }

    /**
     * Create an instance of {@link Wind }
     * 
     */
    public Wind createWind() {
        return new Wind();
    }

    /**
     * Create an instance of {@link Vehicle }
     * 
     */
    public Vehicle createVehicle() {
        return new Vehicle();
    }

    /**
     * Create an instance of {@link PredefinedItineraryVersionedReference }
     * 
     */
    public PredefinedItineraryVersionedReference createPredefinedItineraryVersionedReference() {
        return new PredefinedItineraryVersionedReference();
    }

    /**
     * Create an instance of {@link PollutionInformation }
     * 
     */
    public PollutionInformation createPollutionInformation() {
        return new PollutionInformation();
    }

    /**
     * Create an instance of {@link DistanceFromLinearElementReferent }
     * 
     */
    public DistanceFromLinearElementReferent createDistanceFromLinearElementReferent() {
        return new DistanceFromLinearElementReferent();
    }

    /**
     * Create an instance of {@link AlertCMethod2PrimaryPointLocation }
     * 
     */
    public AlertCMethod2PrimaryPointLocation createAlertCMethod2PrimaryPointLocation() {
        return new AlertCMethod2PrimaryPointLocation();
    }

    /**
     * Create an instance of {@link ManagementExtensionType }
     * 
     */
    public ManagementExtensionType createManagementExtensionType() {
        return new ManagementExtensionType();
    }

    /**
     * Create an instance of {@link Subscription }
     * 
     */
    public Subscription createSubscription() {
        return new Subscription();
    }

    /**
     * Create an instance of {@link RoadSurfaceConditionInformation }
     * 
     */
    public RoadSurfaceConditionInformation createRoadSurfaceConditionInformation() {
        return new RoadSurfaceConditionInformation();
    }

    /**
     * Create an instance of {@link TrafficSpeed }
     * 
     */
    public TrafficSpeed createTrafficSpeed() {
        return new TrafficSpeed();
    }

    /**
     * Create an instance of {@link SituationPublication }
     * 
     */
    public SituationPublication createSituationPublication() {
        return new SituationPublication();
    }

    /**
     * Create an instance of {@link LinearElement }
     * 
     */
    public LinearElement createLinearElement() {
        return new LinearElement();
    }

    /**
     * Create an instance of {@link VmsPictogramExtensionType }
     * 
     */
    public VmsPictogramExtensionType createVmsPictogramExtensionType() {
        return new VmsPictogramExtensionType();
    }

    /**
     * Create an instance of {@link RoadSurfaceConditionMeasurements }
     * 
     */
    public RoadSurfaceConditionMeasurements createRoadSurfaceConditionMeasurements() {
        return new RoadSurfaceConditionMeasurements();
    }

    /**
     * Create an instance of {@link DirectionBearingValue }
     * 
     */
    public DirectionBearingValue createDirectionBearingValue() {
        return new DirectionBearingValue();
    }

    /**
     * Create an instance of {@link MeasuredValue }
     * 
     */
    public MeasuredValue createMeasuredValue() {
        return new MeasuredValue();
    }

    /**
     * Create an instance of {@link TrafficStatus }
     * 
     */
    public TrafficStatus createTrafficStatus() {
        return new TrafficStatus();
    }

    /**
     * Create an instance of {@link VmsUnit }
     * 
     */
    public VmsUnit createVmsUnit() {
        return new VmsUnit();
    }

    /**
     * Create an instance of {@link OperatorAction }
     * 
     */
    public OperatorAction createOperatorAction() {
        return new OperatorAction();
    }

    /**
     * Create an instance of {@link RoadOrCarriagewayOrLaneManagement }
     * 
     */
    public RoadOrCarriagewayOrLaneManagement createRoadOrCarriagewayOrLaneManagement() {
        return new RoadOrCarriagewayOrLaneManagement();
    }

    /**
     * Create an instance of {@link LinearTrafficView }
     * 
     */
    public LinearTrafficView createLinearTrafficView() {
        return new LinearTrafficView();
    }

    /**
     * Create an instance of {@link LinearElementByPoints }
     * 
     */
    public LinearElementByPoints createLinearElementByPoints() {
        return new LinearElementByPoints();
    }

    /**
     * Create an instance of {@link AxleFlowValue }
     * 
     */
    public AxleFlowValue createAxleFlowValue() {
        return new AxleFlowValue();
    }

    /**
     * Create an instance of {@link PredefinedLocation }
     * 
     */
    public PredefinedLocation createPredefinedLocation() {
        return new PredefinedLocation();
    }

    /**
     * Create an instance of {@link TpegNamedOnlyArea }
     * 
     */
    public TpegNamedOnlyArea createTpegNamedOnlyArea() {
        return new TpegNamedOnlyArea();
    }

    /**
     * Create an instance of {@link EmergencyServicesInvolved }
     * 
     */
    public EmergencyServicesInvolved createEmergencyServicesInvolved() {
        return new EmergencyServicesInvolved();
    }

    /**
     * Create an instance of {@link TemperatureValue }
     * 
     */
    public TemperatureValue createTemperatureValue() {
        return new TemperatureValue();
    }

    /**
     * Create an instance of {@link SourceExtensionType }
     * 
     */
    public SourceExtensionType createSourceExtensionType() {
        return new SourceExtensionType();
    }

    /**
     * Create an instance of {@link AlertCLocation }
     * 
     */
    public AlertCLocation createAlertCLocation() {
        return new AlertCLocation();
    }

    /**
     * Create an instance of {@link AbnormalLoadDetails }
     * 
     */
    public AbnormalLoadDetails createAbnormalLoadDetails() {
        return new AbnormalLoadDetails();
    }

    /**
     * Create an instance of {@link Linear }
     * 
     */
    public Linear createLinear() {
        return new Linear();
    }

    /**
     * Create an instance of {@link VisibilityInformation }
     * 
     */
    public VisibilityInformation createVisibilityInformation() {
        return new VisibilityInformation();
    }

    /**
     * Create an instance of {@link MeasurementSiteRecord }
     * 
     */
    public MeasurementSiteRecord createMeasurementSiteRecord() {
        return new MeasurementSiteRecord();
    }

    /**
     * Create an instance of {@link CatalogueReference }
     * 
     */
    public CatalogueReference createCatalogueReference() {
        return new CatalogueReference();
    }

    /**
     * Create an instance of {@link WindInformation }
     * 
     */
    public WindInformation createWindInformation() {
        return new WindInformation();
    }

    /**
     * Create an instance of {@link SpeedFvdOnly }
     * 
     */
    public SpeedFvdOnly createSpeedFvdOnly() {
        return new SpeedFvdOnly();
    }

    /**
     * Create an instance of {@link SpeedCharacteristic }
     * 
     */
    public SpeedCharacteristic createSpeedCharacteristic() {
        return new SpeedCharacteristic();
    }

    /**
     * Create an instance of {@link TrafficFlow }
     * 
     */
    public TrafficFlow createTrafficFlow() {
        return new TrafficFlow();
    }

    /**
     * Create an instance of {@link InfrastructureDamage }
     * 
     */
    public InfrastructureDamage createInfrastructureDamage() {
        return new InfrastructureDamage();
    }

    /**
     * Create an instance of {@link TransitInformation }
     * 
     */
    public TransitInformation createTransitInformation() {
        return new TransitInformation();
    }

    /**
     * Create an instance of {@link LinearElementByCode }
     * 
     */
    public LinearElementByCode createLinearElementByCode() {
        return new LinearElementByCode();
    }

    /**
     * Create an instance of {@link OffsetDistance }
     * 
     */
    public OffsetDistance createOffsetDistance() {
        return new OffsetDistance();
    }

    /**
     * Create an instance of {@link MeasurementSiteTable }
     * 
     */
    public MeasurementSiteTable createMeasurementSiteTable() {
        return new MeasurementSiteTable();
    }

    /**
     * Create an instance of {@link VmsRecord }
     * 
     */
    public VmsRecord createVmsRecord() {
        return new VmsRecord();
    }

    /**
     * Create an instance of {@link FilterExitManagement }
     * 
     */
    public FilterExitManagement createFilterExitManagement() {
        return new FilterExitManagement();
    }

    /**
     * Create an instance of {@link TextPage }
     * 
     */
    public TextPage createTextPage() {
        return new TextPage();
    }

    /**
     * Create an instance of {@link VmsFault }
     * 
     */
    public VmsFault createVmsFault() {
        return new VmsFault();
    }

    /**
     * Create an instance of {@link VmsUnitRecordVersionedReference }
     * 
     */
    public VmsUnitRecordVersionedReference createVmsUnitRecordVersionedReference() {
        return new VmsUnitRecordVersionedReference();
    }

    /**
     * Create an instance of {@link AbnormalTraffic }
     * 
     */
    public AbnormalTraffic createAbnormalTraffic() {
        return new AbnormalTraffic();
    }

    /**
     * Create an instance of {@link Comment }
     * 
     */
    public Comment createComment() {
        return new Comment();
    }

    /**
     * Create an instance of {@link PolygonAreaIndexPointCoordinates }
     * 
     */
    public PolygonAreaIndexPointCoordinates createPolygonAreaIndexPointCoordinates() {
        return new PolygonAreaIndexPointCoordinates();
    }

    /**
     * Create an instance of {@link LifeCycleManagement }
     * 
     */
    public LifeCycleManagement createLifeCycleManagement() {
        return new LifeCycleManagement();
    }

    /**
     * Create an instance of {@link GeographicArea }
     * 
     */
    public GeographicArea createGeographicArea() {
        return new GeographicArea();
    }

    /**
     * Create an instance of {@link ConstructionWorks }
     * 
     */
    public ConstructionWorks createConstructionWorks() {
        return new ConstructionWorks();
    }

    /**
     * Create an instance of {@link Management }
     * 
     */
    public Management createManagement() {
        return new Management();
    }

    /**
     * Create an instance of {@link RoadsideAssistance }
     * 
     */
    public RoadsideAssistance createRoadsideAssistance() {
        return new RoadsideAssistance();
    }

    /**
     * Create an instance of {@link SpillageInformation }
     * 
     */
    public SpillageInformation createSpillageInformation() {
        return new SpillageInformation();
    }

    /**
     * Create an instance of {@link TpegFramedPoint }
     * 
     */
    public TpegFramedPoint createTpegFramedPoint() {
        return new TpegFramedPoint();
    }

    /**
     * Create an instance of {@link RelativeDelays }
     * 
     */
    public RelativeDelays createRelativeDelays() {
        return new RelativeDelays();
    }

    /**
     * Create an instance of {@link StaticCapacity }
     * 
     */
    public StaticCapacity createStaticCapacity() {
        return new StaticCapacity();
    }

    /**
     * Create an instance of {@link Exchange }
     * 
     */
    public Exchange createExchange() {
        return new Exchange();
    }

    /**
     * Create an instance of {@link Target }
     * 
     */
    public Target createTarget() {
        return new Target();
    }

    /**
     * Create an instance of {@link TpegAreaDescriptor }
     * 
     */
    public TpegAreaDescriptor createTpegAreaDescriptor() {
        return new TpegAreaDescriptor();
    }

    /**
     * Create an instance of {@link PredefinedNonOrderedLocationGroup }
     * 
     */
    public PredefinedNonOrderedLocationGroup createPredefinedNonOrderedLocationGroup() {
        return new PredefinedNonOrderedLocationGroup();
    }

    /**
     * Create an instance of {@link TimePeriodByHour }
     * 
     */
    public TimePeriodByHour createTimePeriodByHour() {
        return new TimePeriodByHour();
    }

    /**
     * Create an instance of {@link ReferenceSettings }
     * 
     */
    public ReferenceSettings createReferenceSettings() {
        return new ReferenceSettings();
    }

    /**
     * Create an instance of {@link Validity }
     * 
     */
    public Validity createValidity() {
        return new Validity();
    }

    /**
     * Create an instance of {@link ConcentrationOfVehiclesValue }
     * 
     */
    public ConcentrationOfVehiclesValue createConcentrationOfVehiclesValue() {
        return new ConcentrationOfVehiclesValue();
    }

    /**
     * Create an instance of {@link RoadOperatorServiceDisruption }
     * 
     */
    public RoadOperatorServiceDisruption createRoadOperatorServiceDisruption() {
        return new RoadOperatorServiceDisruption();
    }

    /**
     * Create an instance of {@link SpeedManagement }
     * 
     */
    public SpeedManagement createSpeedManagement() {
        return new SpeedManagement();
    }

    /**
     * Create an instance of {@link ElaboratedDataPublication }
     * 
     */
    public ElaboratedDataPublication createElaboratedDataPublication() {
        return new ElaboratedDataPublication();
    }

    /**
     * Create an instance of {@link AlternateRoute }
     * 
     */
    public AlternateRoute createAlternateRoute() {
        return new AlternateRoute();
    }

    /**
     * Create an instance of {@link Area }
     * 
     */
    public Area createArea() {
        return new Area();
    }

    /**
     * Create an instance of {@link ReturnToNormalStatus }
     * 
     */
    public ReturnToNormalStatus createReturnToNormalStatus() {
        return new ReturnToNormalStatus();
    }

    /**
     * Create an instance of {@link TrafficViewRecord }
     * 
     */
    public TrafficViewRecord createTrafficViewRecord() {
        return new TrafficViewRecord();
    }

    /**
     * Create an instance of {@link IntegerMetreDistanceValue }
     * 
     */
    public IntegerMetreDistanceValue createIntegerMetreDistanceValue() {
        return new IntegerMetreDistanceValue();
    }

    /**
     * Create an instance of {@link PredefinedItinerary }
     * 
     */
    public PredefinedItinerary createPredefinedItinerary() {
        return new PredefinedItinerary();
    }

    /**
     * Create an instance of {@link PublicEventDetails }
     * 
     */
    public PublicEventDetails createPublicEventDetails() {
        return new PublicEventDetails();
    }

    /**
     * Create an instance of {@link SpeedValue }
     * 
     */
    public SpeedValue createSpeedValue() {
        return new SpeedValue();
    }

    /**
     * Create an instance of {@link TemperatureInformation }
     * 
     */
    public TemperatureInformation createTemperatureInformation() {
        return new TemperatureInformation();
    }

    /**
     * Create an instance of {@link IntermediatePointOnLinearElement }
     * 
     */
    public IntermediatePointOnLinearElement createIntermediatePointOnLinearElement() {
        return new IntermediatePointOnLinearElement();
    }

    /**
     * Create an instance of {@link PoorEnvironmentConditions }
     * 
     */
    public PoorEnvironmentConditions createPoorEnvironmentConditions() {
        return new PoorEnvironmentConditions();
    }

    /**
     * Create an instance of {@link PeopleAndVehiclesInvolved }
     * 
     */
    public PeopleAndVehiclesInvolved createPeopleAndVehiclesInvolved() {
        return new PeopleAndVehiclesInvolved();
    }

    /**
     * Create an instance of {@link VmsUnitRecord }
     * 
     */
    public VmsUnitRecord createVmsUnitRecord() {
        return new VmsUnitRecord();
    }

    /**
     * Create an instance of {@link ExtensionType }
     * 
     */
    public ExtensionType createExtensionType() {
        return new ExtensionType();
    }

    /**
     * Create an instance of {@link FloatingPointMetreDistanceValue }
     * 
     */
    public FloatingPointMetreDistanceValue createFloatingPointMetreDistanceValue() {
        return new FloatingPointMetreDistanceValue();
    }

    /**
     * Create an instance of {@link InfrastructureDamageStatus }
     * 
     */
    public InfrastructureDamageStatus createInfrastructureDamageStatus() {
        return new InfrastructureDamageStatus();
    }

    /**
     * Create an instance of {@link ItineraryByIndexedLocations }
     * 
     */
    public ItineraryByIndexedLocations createItineraryByIndexedLocations() {
        return new ItineraryByIndexedLocations();
    }

    /**
     * Create an instance of {@link AlertCMethod4Linear }
     * 
     */
    public AlertCMethod4Linear createAlertCMethod4Linear() {
        return new AlertCMethod4Linear();
    }

    /**
     * Create an instance of {@link AnimalPresenceObstruction }
     * 
     */
    public AnimalPresenceObstruction createAnimalPresenceObstruction() {
        return new AnimalPresenceObstruction();
    }

    /**
     * Create an instance of {@link SignSetting }
     * 
     */
    public SignSetting createSignSetting() {
        return new SignSetting();
    }

    /**
     * Create an instance of {@link Vms }
     * 
     */
    public Vms createVms() {
        return new Vms();
    }

    /**
     * Create an instance of {@link NtisModelVersionInformation }
     * 
     */
    public NtisModelVersionInformation createNtisModelVersionInformation() {
        return new NtisModelVersionInformation();
    }

    /**
     * Create an instance of {@link VmsRecordPictogramDisplayAreaIndexVmsPictogramDisplayCharacteristics }
     * 
     */
    public VmsRecordPictogramDisplayAreaIndexVmsPictogramDisplayCharacteristics createVmsRecordPictogramDisplayAreaIndexVmsPictogramDisplayCharacteristics() {
        return new VmsRecordPictogramDisplayAreaIndexVmsPictogramDisplayCharacteristics();
    }

    /**
     * Create an instance of {@link HeaviestAxleWeightCharacteristic }
     * 
     */
    public HeaviestAxleWeightCharacteristic createHeaviestAxleWeightCharacteristic() {
        return new HeaviestAxleWeightCharacteristic();
    }

    /**
     * Create an instance of {@link PolygonArea }
     * 
     */
    public PolygonArea createPolygonArea() {
        return new PolygonArea();
    }

    /**
     * Create an instance of {@link Accident }
     * 
     */
    public Accident createAccident() {
        return new Accident();
    }

    /**
     * Create an instance of {@link NonOrderedLocationGroupByReference }
     * 
     */
    public NonOrderedLocationGroupByReference createNonOrderedLocationGroupByReference() {
        return new NonOrderedLocationGroupByReference();
    }

    /**
     * Create an instance of {@link TpegOtherPointDescriptor }
     * 
     */
    public TpegOtherPointDescriptor createTpegOtherPointDescriptor() {
        return new TpegOtherPointDescriptor();
    }

    /**
     * Create an instance of {@link TrafficConcentration }
     * 
     */
    public TrafficConcentration createTrafficConcentration() {
        return new TrafficConcentration();
    }

    /**
     * Create an instance of {@link VmsDynamicCharacteristicsPictogramDisplayAreaIndexVmsPictogramDisplayCharacteristics }
     * 
     */
    public VmsDynamicCharacteristicsPictogramDisplayAreaIndexVmsPictogramDisplayCharacteristics createVmsDynamicCharacteristicsPictogramDisplayAreaIndexVmsPictogramDisplayCharacteristics() {
        return new VmsDynamicCharacteristicsPictogramDisplayAreaIndexVmsPictogramDisplayCharacteristics();
    }

    /**
     * Create an instance of {@link AlertCLinearByCode }
     * 
     */
    public AlertCLinearByCode createAlertCLinearByCode() {
        return new AlertCLinearByCode();
    }

    /**
     * Create an instance of {@link TpegNonJunctionPoint }
     * 
     */
    public TpegNonJunctionPoint createTpegNonJunctionPoint() {
        return new TpegNonJunctionPoint();
    }

    /**
     * Create an instance of {@link IndividualLane }
     * 
     */
    public IndividualLane createIndividualLane() {
        return new IndividualLane();
    }

    /**
     * Create an instance of {@link VmsMessageIndexVmsMessage }
     * 
     */
    public VmsMessageIndexVmsMessage createVmsMessageIndexVmsMessage() {
        return new VmsMessageIndexVmsMessage();
    }

    /**
     * Create an instance of {@link EquipmentOrSystemFault }
     * 
     */
    public EquipmentOrSystemFault createEquipmentOrSystemFault() {
        return new EquipmentOrSystemFault();
    }

    /**
     * Create an instance of {@link HeightCharacteristic }
     * 
     */
    public HeightCharacteristic createHeightCharacteristic() {
        return new HeightCharacteristic();
    }

    /**
     * Create an instance of {@link GrossWeightCharacteristic }
     * 
     */
    public GrossWeightCharacteristic createGrossWeightCharacteristic() {
        return new GrossWeightCharacteristic();
    }

    /**
     * Create an instance of {@link VmsMessagePictogramDisplayAreaIndexVmsPictogramDisplayArea }
     * 
     */
    public VmsMessagePictogramDisplayAreaIndexVmsPictogramDisplayArea createVmsMessagePictogramDisplayAreaIndexVmsPictogramDisplayArea() {
        return new VmsMessagePictogramDisplayAreaIndexVmsPictogramDisplayArea();
    }

    /**
     * Create an instance of {@link MultilingualString.Values }
     * 
     */
    public MultilingualString.Values createMultilingualStringValues() {
        return new MultilingualString.Values();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link D2LogicalModel }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://datex2.eu/schema/2/2_0", name = "d2LogicalModel")
    public JAXBElement<D2LogicalModel> createD2LogicalModel(D2LogicalModel value) {
        return new JAXBElement<D2LogicalModel>(_D2LogicalModel_QNAME, D2LogicalModel.class, null, value);
    }

}
