//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.23 at 08:20:34 AM BST 
//


package com.se.datex2.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Defines points for a closed polygon shape describing the area
 * 
 * <p>Java class for PolygonArea complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PolygonArea">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sectionName" type="{http://datex2.eu/schema/2/2_0}MultilingualString" minOccurs="0"/>
 *         &lt;element name="pointCoordinates" type="{http://datex2.eu/schema/2/2_0}_PolygonAreaIndexPointCoordinates" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="polygonAreaExtension" type="{http://datex2.eu/schema/2/2_0}_ExtensionType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PolygonArea", propOrder = {
    "sectionName",
    "pointCoordinates",
    "polygonAreaExtension"
})
public class PolygonArea {

    protected MultilingualString sectionName;
    protected List<PolygonAreaIndexPointCoordinates> pointCoordinates;
    protected ExtensionType polygonAreaExtension;

    /**
     * Gets the value of the sectionName property.
     * 
     * @return
     *     possible object is
     *     {@link MultilingualString }
     *     
     */
    public MultilingualString getSectionName() {
        return sectionName;
    }

    /**
     * Sets the value of the sectionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultilingualString }
     *     
     */
    public void setSectionName(MultilingualString value) {
        this.sectionName = value;
    }

    /**
     * Gets the value of the pointCoordinates property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pointCoordinates property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPointCoordinates().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PolygonAreaIndexPointCoordinates }
     * 
     * 
     */
    public List<PolygonAreaIndexPointCoordinates> getPointCoordinates() {
        if (pointCoordinates == null) {
            pointCoordinates = new ArrayList<PolygonAreaIndexPointCoordinates>();
        }
        return this.pointCoordinates;
    }

    /**
     * Gets the value of the polygonAreaExtension property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionType }
     *     
     */
    public ExtensionType getPolygonAreaExtension() {
        return polygonAreaExtension;
    }

    /**
     * Sets the value of the polygonAreaExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionType }
     *     
     */
    public void setPolygonAreaExtension(ExtensionType value) {
        this.polygonAreaExtension = value;
    }

}
