//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.30 at 10:48:06 AM GMT 
//


package com.se.datex2.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PositionRelativeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PositionRelativeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="above"/>
 *     &lt;enumeration value="below"/>
 *     &lt;enumeration value="toTheLeft"/>
 *     &lt;enumeration value="toTheRight"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PositionRelativeEnum")
@XmlEnum
public enum PositionRelativeEnum {


    /**
     * Positioned above relative item.
     * 
     */
    @XmlEnumValue("above")
    ABOVE("above"),

    /**
     * Positioned below relative item.
     * 
     */
    @XmlEnumValue("below")
    BELOW("below"),

    /**
     * Positioned to the left of relative item.
     * 
     */
    @XmlEnumValue("toTheLeft")
    TO_THE_LEFT("toTheLeft"),

    /**
     * Positioned to the right of relative item.
     * 
     */
    @XmlEnumValue("toTheRight")
    TO_THE_RIGHT("toTheRight");
    private final String value;

    PositionRelativeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PositionRelativeEnum fromValue(String v) {
        for (PositionRelativeEnum c: PositionRelativeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
