//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.30 at 10:48:06 AM GMT 
//


package com.se.datex2.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SeverityEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SeverityEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="highest"/>
 *     &lt;enumeration value="high"/>
 *     &lt;enumeration value="medium"/>
 *     &lt;enumeration value="low"/>
 *     &lt;enumeration value="lowest"/>
 *     &lt;enumeration value="none"/>
 *     &lt;enumeration value="unknown"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SeverityEnum")
@XmlEnum
public enum SeverityEnum {


    /**
     * Perceived by supplier as being of the highest level.
     * 
     */
    @XmlEnumValue("highest")
    HIGHEST("highest"),

    /**
     * Perceived by supplier as being of a high level.
     * 
     */
    @XmlEnumValue("high")
    HIGH("high"),

    /**
     * Perceived by supplier as being of a medium level.
     * 
     */
    @XmlEnumValue("medium")
    MEDIUM("medium"),

    /**
     * Perceived by supplier as being of a low level.
     * 
     */
    @XmlEnumValue("low")
    LOW("low"),

    /**
     * Perceived by supplier as being of the lowest discernible level.
     * 
     */
    @XmlEnumValue("lowest")
    LOWEST("lowest"),

    /**
     * Perceived by supplier as having a severity rating of none.
     * 
     */
    @XmlEnumValue("none")
    NONE("none"),

    /**
     * Perceived by supplier as being of an unknown level.
     * 
     */
    @XmlEnumValue("unknown")
    UNKNOWN("unknown");
    private final String value;

    SeverityEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SeverityEnum fromValue(String v) {
        for (SeverityEnum c: SeverityEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
