//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.23 at 08:20:34 AM BST 
//


package com.se.datex2.schema;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * The Static Capacity of the linear section within a linear element.  Static Capacity is defined as the maximum flow of vehicles that all lanes of a section of carriageway can accommodate if no other events or conditions are affecting the traffic flow.
 * 
 * <p>Java class for StaticCapacity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StaticCapacity">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="exitPointStaticCapacity" type="{http://datex2.eu/schema/2/2_0}VehiclesPerHour" minOccurs="0"/>
 *         &lt;element name="midPointStaticCapacity" type="{http://datex2.eu/schema/2/2_0}VehiclesPerHour" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StaticCapacity", propOrder = {
    "exitPointStaticCapacity",
    "midPointStaticCapacity"
})
public class StaticCapacity {

    protected BigInteger exitPointStaticCapacity;
    protected BigInteger midPointStaticCapacity;

    /**
     * Gets the value of the exitPointStaticCapacity property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getExitPointStaticCapacity() {
        return exitPointStaticCapacity;
    }

    /**
     * Sets the value of the exitPointStaticCapacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setExitPointStaticCapacity(BigInteger value) {
        this.exitPointStaticCapacity = value;
    }

    /**
     * Gets the value of the midPointStaticCapacity property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMidPointStaticCapacity() {
        return midPointStaticCapacity;
    }

    /**
     * Sets the value of the midPointStaticCapacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMidPointStaticCapacity(BigInteger value) {
        this.midPointStaticCapacity = value;
    }

}
