//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.30 at 10:48:06 AM GMT 
//


package com.se.datex2.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VmsDatexSupplementalPictogramEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="VmsDatexSupplementalPictogramEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="distanceToTheBeginningofTheApplicationZone"/>
 *     &lt;enumeration value="exceptAnyPowerDrivenVehicleDrawingTrailer"/>
 *     &lt;enumeration value="exceptBus"/>
 *     &lt;enumeration value="exceptGoodsVehicles"/>
 *     &lt;enumeration value="exceptSemiTrailer"/>
 *     &lt;enumeration value="exceptVehiclesCarryingDangerousGoods"/>
 *     &lt;enumeration value="inCaseOfIceOrSnow"/>
 *     &lt;enumeration value="lengthOfTheApplicationZone"/>
 *     &lt;enumeration value="restrictedToAnyPowerDrivenVehicleDrawingTrailer"/>
 *     &lt;enumeration value="restricetdToBus"/>
 *     &lt;enumeration value="restrictedToGoodsVehicles"/>
 *     &lt;enumeration value="restrictedToSemiTrailer"/>
 *     &lt;enumeration value="restrictedToVehiclesCarryingDangerousGoods"/>
 *     &lt;enumeration value="maintenanceVehicles"/>
 *     &lt;enumeration value="snowPloughs"/>
 *     &lt;enumeration value="other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "VmsDatexSupplementalPictogramEnum")
@XmlEnum
public enum VmsDatexSupplementalPictogramEnum {


    /**
     * Distance to the beginning of the application zone.
     * 
     */
    @XmlEnumValue("distanceToTheBeginningofTheApplicationZone")
    DISTANCE_TO_THE_BEGINNINGOF_THE_APPLICATION_ZONE("distanceToTheBeginningofTheApplicationZone"),

    /**
     * Except any power driven vehicle drawing a trailer.
     * 
     */
    @XmlEnumValue("exceptAnyPowerDrivenVehicleDrawingTrailer")
    EXCEPT_ANY_POWER_DRIVEN_VEHICLE_DRAWING_TRAILER("exceptAnyPowerDrivenVehicleDrawingTrailer"),

    /**
     * Except for buses.
     * 
     */
    @XmlEnumValue("exceptBus")
    EXCEPT_BUS("exceptBus"),

    /**
     * Except for goods vehicles.
     * 
     */
    @XmlEnumValue("exceptGoodsVehicles")
    EXCEPT_GOODS_VEHICLES("exceptGoodsVehicles"),

    /**
     * Except for semi trailers (i.e. any trailer designed to be coupled to a motor vehicle in such a way that part of its weight and that of its load is borne by the motor vehicle).
     * 
     */
    @XmlEnumValue("exceptSemiTrailer")
    EXCEPT_SEMI_TRAILER("exceptSemiTrailer"),

    /**
     * Except for vehicles carrying dangerous goods (i.e. for which special sign plating is prescribed).
     * 
     */
    @XmlEnumValue("exceptVehiclesCarryingDangerousGoods")
    EXCEPT_VEHICLES_CARRYING_DANGEROUS_GOODS("exceptVehiclesCarryingDangerousGoods"),

    /**
     * In case of ice or snow.
     * 
     */
    @XmlEnumValue("inCaseOfIceOrSnow")
    IN_CASE_OF_ICE_OR_SNOW("inCaseOfIceOrSnow"),

    /**
     * Length of the applicable zone.
     * 
     */
    @XmlEnumValue("lengthOfTheApplicationZone")
    LENGTH_OF_THE_APPLICATION_ZONE("lengthOfTheApplicationZone"),

    /**
     * Restricted to any power driven vehicle drawing a trailer.
     * 
     */
    @XmlEnumValue("restrictedToAnyPowerDrivenVehicleDrawingTrailer")
    RESTRICTED_TO_ANY_POWER_DRIVEN_VEHICLE_DRAWING_TRAILER("restrictedToAnyPowerDrivenVehicleDrawingTrailer"),

    /**
     * Restricted to buses.
     * 
     */
    @XmlEnumValue("restricetdToBus")
    RESTRICETD_TO_BUS("restricetdToBus"),

    /**
     * Restricted to goods vehicles.
     * 
     */
    @XmlEnumValue("restrictedToGoodsVehicles")
    RESTRICTED_TO_GOODS_VEHICLES("restrictedToGoodsVehicles"),

    /**
     * Restricted to semi trailers (i.e. any trailer designed to be coupled to a motor vehicle in such a way that part of its wieght and that of its load is borne by the motor vehicle).
     * 
     */
    @XmlEnumValue("restrictedToSemiTrailer")
    RESTRICTED_TO_SEMI_TRAILER("restrictedToSemiTrailer"),

    /**
     * Restricted to vehicles carrying dangerous goods (i.e. for which special sign plating is prescribed).
     * 
     */
    @XmlEnumValue("restrictedToVehiclesCarryingDangerousGoods")
    RESTRICTED_TO_VEHICLES_CARRYING_DANGEROUS_GOODS("restrictedToVehiclesCarryingDangerousGoods"),

    /**
     * Maintenance vehicles.
     * 
     */
    @XmlEnumValue("maintenanceVehicles")
    MAINTENANCE_VEHICLES("maintenanceVehicles"),

    /**
     * Snow ploughs.
     * 
     */
    @XmlEnumValue("snowPloughs")
    SNOW_PLOUGHS("snowPloughs"),

    /**
     * Other than as defined in this enumeration.
     * 
     */
    @XmlEnumValue("other")
    OTHER("other");
    private final String value;

    VmsDatexSupplementalPictogramEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static VmsDatexSupplementalPictogramEnum fromValue(String v) {
        for (VmsDatexSupplementalPictogramEnum c: VmsDatexSupplementalPictogramEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
