//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.23 at 08:20:34 AM BST 
//


package com.se.datex2.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * An additional pictogram that is displayed in the panel which is supplemental to the associated pictogram display.
 * 
 * <p>Java class for VmsSupplementaryPictogram complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VmsSupplementaryPictogram">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="supplementaryPictogramDescription" type="{http://datex2.eu/schema/2/2_0}VmsDatexSupplementalPictogramEnum" minOccurs="0"/>
 *         &lt;element name="supplementaryPictogramCode" type="{http://datex2.eu/schema/2/2_0}String" minOccurs="0"/>
 *         &lt;element name="supplementaryPictogramUrl" type="{http://datex2.eu/schema/2/2_0}Url" minOccurs="0"/>
 *         &lt;element name="additionalSupplementaryPictogramDescription" type="{http://datex2.eu/schema/2/2_0}MultilingualString" minOccurs="0"/>
 *         &lt;element name="pictogramFlashing" type="{http://datex2.eu/schema/2/2_0}Boolean" minOccurs="0"/>
 *         &lt;element name="vmsSupplementaryPictogramExtension" type="{http://datex2.eu/schema/2/2_0}_ExtensionType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VmsSupplementaryPictogram", propOrder = {
    "supplementaryPictogramDescription",
    "supplementaryPictogramCode",
    "supplementaryPictogramUrl",
    "additionalSupplementaryPictogramDescription",
    "pictogramFlashing",
    "vmsSupplementaryPictogramExtension"
})
public class VmsSupplementaryPictogram {

    protected VmsDatexSupplementalPictogramEnum supplementaryPictogramDescription;
    protected String supplementaryPictogramCode;
    protected String supplementaryPictogramUrl;
    protected MultilingualString additionalSupplementaryPictogramDescription;
    protected Boolean pictogramFlashing;
    protected ExtensionType vmsSupplementaryPictogramExtension;

    /**
     * Gets the value of the supplementaryPictogramDescription property.
     * 
     * @return
     *     possible object is
     *     {@link VmsDatexSupplementalPictogramEnum }
     *     
     */
    public VmsDatexSupplementalPictogramEnum getSupplementaryPictogramDescription() {
        return supplementaryPictogramDescription;
    }

    /**
     * Sets the value of the supplementaryPictogramDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link VmsDatexSupplementalPictogramEnum }
     *     
     */
    public void setSupplementaryPictogramDescription(VmsDatexSupplementalPictogramEnum value) {
        this.supplementaryPictogramDescription = value;
    }

    /**
     * Gets the value of the supplementaryPictogramCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplementaryPictogramCode() {
        return supplementaryPictogramCode;
    }

    /**
     * Sets the value of the supplementaryPictogramCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplementaryPictogramCode(String value) {
        this.supplementaryPictogramCode = value;
    }

    /**
     * Gets the value of the supplementaryPictogramUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplementaryPictogramUrl() {
        return supplementaryPictogramUrl;
    }

    /**
     * Sets the value of the supplementaryPictogramUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplementaryPictogramUrl(String value) {
        this.supplementaryPictogramUrl = value;
    }

    /**
     * Gets the value of the additionalSupplementaryPictogramDescription property.
     * 
     * @return
     *     possible object is
     *     {@link MultilingualString }
     *     
     */
    public MultilingualString getAdditionalSupplementaryPictogramDescription() {
        return additionalSupplementaryPictogramDescription;
    }

    /**
     * Sets the value of the additionalSupplementaryPictogramDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultilingualString }
     *     
     */
    public void setAdditionalSupplementaryPictogramDescription(MultilingualString value) {
        this.additionalSupplementaryPictogramDescription = value;
    }

    /**
     * Gets the value of the pictogramFlashing property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPictogramFlashing() {
        return pictogramFlashing;
    }

    /**
     * Sets the value of the pictogramFlashing property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPictogramFlashing(Boolean value) {
        this.pictogramFlashing = value;
    }

    /**
     * Gets the value of the vmsSupplementaryPictogramExtension property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionType }
     *     
     */
    public ExtensionType getVmsSupplementaryPictogramExtension() {
        return vmsSupplementaryPictogramExtension;
    }

    /**
     * Sets the value of the vmsSupplementaryPictogramExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionType }
     *     
     */
    public void setVmsSupplementaryPictogramExtension(ExtensionType value) {
        this.vmsSupplementaryPictogramExtension = value;
    }

}
